require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TalesController do

  # This should return the minimal set of attributes required to create a valid
  # Tale. As you add validations to Tale, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TalesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tales as @tales" do
      tale = Tale.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tales).should eq([tale])
    end
  end

  describe "GET show" do
    it "assigns the requested tale as @tale" do
      tale = Tale.create! valid_attributes
      get :show, {:id => tale.to_param}, valid_session
      assigns(:tale).should eq(tale)
    end
  end

  describe "GET new" do
    it "assigns a new tale as @tale" do
      get :new, {}, valid_session
      assigns(:tale).should be_a_new(Tale)
    end
  end

  describe "GET edit" do
    it "assigns the requested tale as @tale" do
      tale = Tale.create! valid_attributes
      get :edit, {:id => tale.to_param}, valid_session
      assigns(:tale).should eq(tale)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tale" do
        expect {
          post :create, {:tale => valid_attributes}, valid_session
        }.to change(Tale, :count).by(1)
      end

      it "assigns a newly created tale as @tale" do
        post :create, {:tale => valid_attributes}, valid_session
        assigns(:tale).should be_a(Tale)
        assigns(:tale).should be_persisted
      end

      it "redirects to the created tale" do
        post :create, {:tale => valid_attributes}, valid_session
        response.should redirect_to(Tale.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tale as @tale" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tale.any_instance.stub(:save).and_return(false)
        post :create, {:tale => {}}, valid_session
        assigns(:tale).should be_a_new(Tale)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tale.any_instance.stub(:save).and_return(false)
        post :create, {:tale => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tale" do
        tale = Tale.create! valid_attributes
        # Assuming there are no other tales in the database, this
        # specifies that the Tale created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tale.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tale.to_param, :tale => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tale as @tale" do
        tale = Tale.create! valid_attributes
        put :update, {:id => tale.to_param, :tale => valid_attributes}, valid_session
        assigns(:tale).should eq(tale)
      end

      it "redirects to the tale" do
        tale = Tale.create! valid_attributes
        put :update, {:id => tale.to_param, :tale => valid_attributes}, valid_session
        response.should redirect_to(tale)
      end
    end

    describe "with invalid params" do
      it "assigns the tale as @tale" do
        tale = Tale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tale.any_instance.stub(:save).and_return(false)
        put :update, {:id => tale.to_param, :tale => {}}, valid_session
        assigns(:tale).should eq(tale)
      end

      it "re-renders the 'edit' template" do
        tale = Tale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tale.any_instance.stub(:save).and_return(false)
        put :update, {:id => tale.to_param, :tale => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tale" do
      tale = Tale.create! valid_attributes
      expect {
        delete :destroy, {:id => tale.to_param}, valid_session
      }.to change(Tale, :count).by(-1)
    end

    it "redirects to the tales list" do
      tale = Tale.create! valid_attributes
      delete :destroy, {:id => tale.to_param}, valid_session
      response.should redirect_to(tales_url)
    end
  end

end
